---

ubuntu_release: "{{ ansible_distribution_release }}"

apt_install_repositories:
  - repo: "deb http://repository.spotify.com stable non-free"
    key: BBEBDCB318AD50EC6865090613B00F1FD2C19886
  - repo: "deb http://dl.google.com/linux/chrome/deb stable main"
    key:
      id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
      url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"

copy_files:
  - src: powertop.systemd.service
    dest: /etc/systemd/system/powertop.service

apt_install:
  # Editors
  - vim-gtk3-py2

  # Power Management
  - tlp
  - tlp-rdw
  - powertop

  # Graphics
  - gimp

  # Services
  - nautilus-dropbox

  # Media
  - spotify-client
  - vlc

  # Browsers
  - google-chrome-stable

  # Handy tools
  - xclip

vpn_connections:
  - remote: uk-london.privateinternetaccess.com 
    name: 'PIA UK London'
  - remote: uk-southampton.privateinternetaccess.com 
    name: 'PIA UK Southhampton'
  - remote: nl.privateinternetaccess.com 
    name: 'PIA Netherlands'
  - remote: sweden.privateinternetaccess.com 
    name: 'PIA Sweden'
  - remote: ro.privateinternetaccess.com 
    name: 'PIA Romania'
  - remote: us-east.privateinternetaccess.com 
    name: 'PIA US East'
  - remote: us-newyorkcity.privateinternetaccess.com 
    name: 'PIA US New York City'
