---

user: michael

ubuntu_release: "{{ ansible_distribution_release }}"

apt_install_repositories:
  - repo: "deb http://repository.spotify.com stable non-free"
    key: BBEBDCB318AD50EC6865090613B00F1FD2C19886
  - repo: "deb http://dl.google.com/linux/chrome/deb stable main"
    key:
      id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
      url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
  - 'ppa:webupd8team/atom'
  - 'ppa:neovim-ppa/unstable'

apt_install:
  # Look and feel
  - arc-theme
  - variety

  # Terminal
  - tilda

  # Editors
  - vim-gtk-py2
  - neovim
  - atom
  - arduino

  # Power Management
  - tlp
  - tlp-rdw
  - powertop

  # Graphics
  - gimp

  # Services
  - nautilus-dropbox

  # Media
  - spotify-client
  - vlc

  # Browsers
  - google-chrome-stable

  # Handy tools
  - xclip
  - gparted

  # Runtimes
  - cmake
  - gcc
  - g++

git_repos:
  - repo: https://github.com/ryanoasis/nerd-fonts
    path: ~/.repos/nerd-fonts
  - repo: https://github.com/aaron-williamson/base16-gnome-terminal
    path: ~/.repos/base16-gnome
  - repo: https://github.com/chriskempson/base16-shell
    path: ~/.repos/base16-shell

copy_files:
  - src: powertop.systemd.service
    dest: /etc/systemd/system/powertop.service
    owner: root
    group: root

link_files:
  - src: "~/.repos/nerd-fonts/patched-fonts"
    dest: "~/.local/share/fonts/nerd-fonts"
  - src: "~/laptop/files/variety.conf"
    dest: "~/.config/variety/variety.conf"
  - src: "~/laptop/files/tilda_config"
    dest: "~/.config/tilda/config_0"

gsettings:
  - schema: 'org.gnome.desktop.interface'
    settings:
      - key: 'gtk-theme'
        value: 'Arc-Darker'
      - key: 'monospace-font-name'
        value: 'Knack Nerd Font 13'
  - schema: 'org.gnome.desktop.input-sources'
    settings:
      - key: 'xkb-options'
        value: "['caps:escape']"
  - schema: 'org.gnome.desktop.peripherals.keyboard'
    settings:
      - key: 'repeat-interval'
        value: '15'
      - key: 'delay'
        value: '250'
  - schema: 'org.gnome.desktop.wm.preferences'
    settings:
      - key: 'button-layout'
        value: 'close,maximize,minimize:appmenu'

vpn_connections:
  - remote: uk-london.privateinternetaccess.com 
    name: 'PIA UK London'
  - remote: uk-southampton.privateinternetaccess.com 
    name: 'PIA UK Southhampton'
  - remote: nl.privateinternetaccess.com 
    name: 'PIA Netherlands'
  - remote: sweden.privateinternetaccess.com 
    name: 'PIA Sweden'
  - remote: ro.privateinternetaccess.com 
    name: 'PIA Romania'
  - remote: us-east.privateinternetaccess.com 
    name: 'PIA US East'
  - remote: us-newyorkcity.privateinternetaccess.com 
    name: 'PIA US New York City'
