---

user: michael

ubuntu_release: "{{ ansible_distribution_release }}"

apt_upgrade: false

apt_install:
  # Look and feel
  - arc-theme
  - caffeine

  # Terminal
  - tilda
  - zsh

  # Editors
  - vim-gtk
  - neovim

  # Power Management
  - tlp
  - tlp-rdw
  - powertop

  # Graphics
  - gimp

  # Services
  - nautilus-dropbox
  - chrome-gnome-shell

  # Media
  - vlc

  # Handy tools
  - xclip
  - gparted
  - exuberant-ctags
  - ack

  # Runtimes
  - cmake
  - gcc
  - g++
  - ruby-dev
  - docker

  # Map mouse buttons
  - xbindkeys
  - xdotool

git_repos:
  - repo: https://github.com/ryanoasis/nerd-fonts
    path: ~/.repos/nerd-fonts
  - repo: https://github.com/aaron-williamson/base16-gnome-terminal
    path: ~/.repos/base16-gnome
  - repo: https://github.com/zsh-users/zsh-completions
    path: ~/.repos/zsh-completions
  - repo: https://github.com/chriskempson/base16-shell
    path: ~/.repos/base16-shell

link_files:
  - src: "~/.repos/nerd-fonts/patched-fonts"
    dest: "~/.local/share/fonts/nerd-fonts"
  - src: "~/.laptop/files/tilda_config"
    dest: "~/.config/tilda/config_0"

gsettings:
  - schema: 'org.gnome.desktop.interface'
    settings:
      - key: 'gtk-theme'
        value: 'Arc-Darker'
      - key: 'monospace-font-name'
        value: 'Hack Nerd Font 13'
  - schema: 'org.gnome.desktop.input-sources'
    settings:
      - key: 'xkb-options'
        value: "['caps:escape']"
  - schema: 'org.gnome.desktop.peripherals.keyboard'
    settings:
      - key: 'repeat-interval'
        value: '15'
      - key: 'delay'
        value: '250'
  - schema: 'org.gnome.desktop.wm.preferences'
    settings:
      - key: 'button-layout'
        value: 'close,maximize,minimize:appmenu'
