---

- hosts: all
  vars_files:
    - vars/local.yml
  roles:
    - role: michaeldfallen.apt
      become: yes
    - role: michaeldfallen.scm_repos
    - role: michaeldfallen.pia
    - role: michaeldfallen.dotfiles
    - role: michaeldfallen.gsettings
    - role: michaeldfallen.run_once
      vars:
        scripts: "{{ post_run_scripts | default([])}}"
