---

- hosts: all
  vars_files:
    - vars/local.yml
  roles:
    - role: michaeldfallen.apt
      become: yes
    - role: michaeldfallen.scm_repos
    - role: michaeldfallen.pia
    - role: michaeldfallen.dotfiles
