---

- name: michaeldfallen.apt
  src: https://github.com/michaeldfallen/ansible-role-apt

- name: michaeldfallen.pia
  src: https://github.com/michaeldfallen/ansible-pia-vpn

- name: michaeldfallen.dotfiles
  src: https://github.com/michaeldfallen/ansible-role-dotfiles

- name: michaeldfallen.gsettings
  src: https://github.com/michaeldfallen/ansible-role-gsettings

- name: michaeldfallen.scm_repos
  src: https://github.com/michaeldfallen/ansible-role-scm-repos
